server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdspider?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#logging:
#  level:
#    com.ks.* : debug
